@extends('admin.layout')
@section('title', 'Giao dịch')
@section('content')
    <div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-[.18em] text-violet-300">Bán vé</p><h1 class="mt-2 text-3xl font-bold">Giao dịch và đơn đặt vé</h1><p class="mt-2 text-sm text-neutral-400">Phân loại thanh toán và xử lý yêu cầu hủy/hoàn tiền.</p><p class="mt-2 text-xs text-amber-200">Cổng thanh toán chưa tích hợp. Chỉ ghi nhận thanh toán hoặc hoàn tiền sau khi đã kiểm tra giao dịch thực tế.</p></div><a href="{{ route('admin.orders.create') }}" class="rounded-full bg-violet-600 px-5 py-3 text-sm font-bold hover:bg-violet-500">+ Tạo đơn đặt vé</a></div>
    <form method="GET" action="{{ route('admin.orders') }}" class="mb-5 grid gap-3 rounded-2xl border border-white/10 bg-neutral-900 p-4 sm:grid-cols-2 xl:grid-cols-5">
        <input type="search" name="q" value="{{ request('q') }}" placeholder="Mã đơn, tên hoặc email" aria-label="Tìm giao dịch" class="w-full rounded-xl border border-white/10 bg-neutral-950 px-4 py-2.5 text-sm outline-none focus:border-violet-400">
        <select name="status" aria-label="Trạng thái thanh toán" class="w-full rounded-xl border border-white/10 bg-neutral-950 px-4 py-2.5 text-sm outline-none focus:border-violet-400"><option value="">Tất cả trạng thái</option><option value="pending" @selected(request('status') === 'pending')>Chưa thanh toán</option><option value="confirmed" @selected(request('status') === 'confirmed')>Đã thanh toán</option><option value="refund_pending" @selected(request('status') === 'refund_pending')>Chờ hoàn tiền</option><option value="refunded" @selected(request('status') === 'refunded')>Đã hoàn tiền</option><option value="cancelled" @selected(request('status') === 'cancelled')>Đã hủy</option></select>
        <label class="text-xs text-neutral-400">Từ ngày<input type="date" name="from" value="{{ request('from') }}" class="mt-1 block w-full rounded-xl border border-white/10 bg-neutral-950 px-3 py-2.5 text-sm text-white"></label>
        <label class="text-xs text-neutral-400">Đến ngày<input type="date" name="to" value="{{ request('to') }}" class="mt-1 block w-full rounded-xl border border-white/10 bg-neutral-950 px-3 py-2.5 text-sm text-white"></label>
        <button class="self-end rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold hover:bg-violet-500">Lọc giao dịch</button>
        @if (request()->hasAny(['q', 'status', 'from', 'to']))<a href="{{ route('admin.orders') }}" class="rounded-xl border border-white/15 px-5 py-2.5 text-center text-sm hover:bg-white/5">Xóa bộ lọc</a>@endif
    </form>
    <p class="mb-3 text-sm text-neutral-400">{{ $orders->total() }} giao dịch</p>
    <div class="space-y-4">
        @forelse ($orders as $order)
            <article class="rounded-2xl border border-white/10 bg-neutral-900 p-5">
                <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="font-bold">{{ $order->code }} <span class="ml-2 rounded-full px-2.5 py-1 text-xs font-medium {{ ['pending' => 'bg-amber-300/10 text-amber-200', 'confirmed' => 'bg-emerald-300/10 text-emerald-200', 'refund_pending' => 'bg-amber-300/10 text-amber-200', 'refunded' => 'bg-sky-300/10 text-sky-200', 'cancelled' => 'bg-rose-300/10 text-rose-200'][$order->status] }}">{{ ['pending' => 'Chưa thanh toán', 'confirmed' => 'Đã thanh toán', 'refund_pending' => 'Chờ hoàn tiền', 'refunded' => 'Đã hoàn tiền', 'cancelled' => 'Đã hủy'][$order->status] }}</span></h2><p class="mt-2 text-sm text-neutral-400">{{ $order->user->name }} · {{ $order->user->email }} · {{ $order->created_at->format('d/m/Y H:i') }}</p></div><p class="text-xl font-bold text-violet-300">{{ number_format($order->total, 0, ',', '.') }} ₫</p></div>
                <div class="mt-4 divide-y divide-white/5 rounded-xl border border-white/10 px-4">@foreach ($order->items as $item)<div class="flex flex-wrap justify-between gap-2 py-3 text-sm"><span>{{ $item->ticket_name }} × {{ $item->quantity }}</span><span class="text-neutral-300">{{ number_format($item->subtotal, 0, ',', '.') }} ₫</span></div>@endforeach</div>
                @if ($order->status === 'pending')<div class="mt-4 flex flex-wrap justify-end gap-2"><form method="POST" action="{{ route('admin.orders.update', $order) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="cancelled"><button class="rounded-full border border-rose-400/25 px-4 py-2 text-sm font-semibold text-rose-300 hover:bg-rose-400/10">Hủy đơn chưa thanh toán</button></form><form method="POST" action="{{ route('admin.orders.update', $order) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="confirmed"><button class="rounded-full bg-emerald-600 px-4 py-2 text-sm font-semibold hover:bg-emerald-500">Ghi nhận đã thanh toán</button></form></div>
                @elseif ($order->status === 'confirmed')<form method="POST" action="{{ route('admin.orders.update', $order) }}" class="mt-4 flex justify-end">@csrf @method('PATCH')<input type="hidden" name="status" value="refund_pending"><button class="rounded-full border border-amber-300/25 px-4 py-2 text-sm font-semibold text-amber-200 hover:bg-amber-300/10">Hủy đơn, chuyển chờ hoàn tiền</button></form>
                @elseif ($order->status === 'refund_pending')<div class="mt-4 flex flex-wrap justify-end gap-2"><form method="POST" action="{{ route('admin.orders.update', $order) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="confirmed"><button class="rounded-full border border-white/15 px-4 py-2 text-sm hover:bg-white/5">Không duyệt hoàn tiền</button></form><form method="POST" action="{{ route('admin.orders.update', $order) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="refunded"><button class="rounded-full bg-sky-700 px-4 py-2 text-sm font-semibold hover:bg-sky-600">Ghi nhận đã hoàn tiền</button></form></div>@endif
            </article>
        @empty<div class="rounded-2xl border border-dashed border-white/15 p-12 text-center text-neutral-400">Không tìm thấy giao dịch phù hợp.</div>@endforelse
    </div>
    <div class="mt-6">{{ $orders->links() }}</div>
@endsection
